<template>
  <div>
    <v-card flat >
      <v-toolbar flat >
        <v-autocomplete
          dense
          v-model="userselect"
          label="Search User"
          outlined
          item-text="full_user_name"
          item-value="user_id"
          :items="userArray"
          :search-input.sync="searchuser"
          hide-no-data
          style="max-width: 200px"
          class="mr-2 mt-6"
          placeholder="Min 3 Character"
          hide-selected
          return-object
        />
        <v-btn
          depressed
          @click="generatereport()"
          dark
          :loading="buttonload"
          class="text-capitalize cardCss"
        >
          Generate Report
        </v-btn>
      </v-toolbar>
      <v-card-text>
        <v-data-table
          :headers="ticketHeaders"
          :fixed-header="fixed"
          :loading="tableLoading"
          :items="ticketRecords"
          :footer-props="{
            itemsPerPageOptions: [10, 20],
          }"
          :items-per-page="0"
          dense
          class="elevation-1 dtwidth"
        >
          <template v-slot:[`item.progressing_status`]="{ item }">
            <span
              v-if="item.progressing_status == 'COMPLETED'"
              class="green--text"
              >{{ item.progressing_status }}</span
            >
            <span v-else class="orange--text">{{
              item.progressing_status
            }}</span>
          </template>

          <template v-slot:[`item.report_created_on`]="{ item }">
            <span v-text="get_dateformate(item.report_created_on)"></span>
          </template>
          <template v-slot:[`item.generationreport_url`]="{ item }">
            <v-tooltip bottom>
              <template #activator="{ on }">
                <div
                  v-on="on"
                  v-show="item.generationreport_url != undefined"
                  @click="download_invoice(item)"
                >
                  <v-icon
                    ref="downloadButton"
                    v-on="on"
                    small
                    class="mr-1"
                    color="primaryColor"
                    >mdi-download
                  </v-icon>
                </div>
                <span
                  v-show="item.generationreport_url == undefined"
                  class="ml-2"
                  >-</span
                >
              </template>

              <span
                v-if="
                  item.generationreport_url != null ||
                  item.generationreport_url != undefined
                "
                class="white--text"
                >Download</span
              >
            </v-tooltip>
          </template>
        </v-data-table>
      </v-card-text>
    </v-card>
    <SnackBar :SnackBarComponent="SnackBarComponent" />
  </div>
</template>

<script>
import { list_ticket_mangement_reports } from "@/graphql/queries.js";
import { ticket_management_reports } from "@/graphql/mutations.js";
import { get_all_org_users } from "@/mixins/GetUsersDropdown.js";
import { formatedatetime } from "@/JsonFiles/DateFormate.js";
import SnackBar from "@/components/SnackBar.vue";
import axios from "axios";
import { API, graphqlOperation } from "aws-amplify";
const FileSaver = require("file-saver");
export default {
  components: {
    SnackBar,
  },
  mixins: [get_all_org_users],
  data() {
    return {
      fixed: true,
      userselect: "",
      userArray: [],
      SnackBarComponent: {},
      buttonload: false,
      searchuser: "",
      ticketRecords: [],
      tableLoading: false,
      ticketHeaders: [
        { text: "Name", value: "report_type_name", sortable: false },
        { text: "Generated on", value: "report_created_on" },
        { text: "Generated By", value: "report_generated_by" },

        { text: "Status", value: "progressing_status", sortable: false },
        { text: "Report", value: "generationreport_url", sortable: false },
      ],
    };
  },
  async created() {
    await this.get_all_org_users();
    await this.get_report();
    await this.fetch_user_data();
  },
  methods: {
    async get_report() {
      this.tableLoading = true;
      var data = this.$store.getters.GetUserObj;
      try {
        let result = await API.graphql(
          graphqlOperation(list_ticket_mangement_reports, {
            input: {
              organization_id: data.organization.organization_id,
              limit: 100,
            },
          })
        );
        this.tableLoading = false;

        var response = JSON.parse(result.data.list_ticket_mangement_reports);

        if (response.Status == "SUCCESS") {
          this.tableLoading = false;
          this.ticketRecords = response.data;
        } else {
          this.tableLoading = false;
        }
        // this.ticketRecords = response;
      } catch (error) {
        this.tableLoading = false;

        this.SnackBarComponent = {
          SnackbarVmodel: true,
          SnackbarColor: "red",
          SnackbarText: error.errors[0].message,
          timeout: 5000,
          Top: true,
        };
      }
    },
    async generatereport() {
      this.buttonload = true;
      var data = this.$store.getters.GetUserObj;
      try {
        let result = await API.graphql(
          graphqlOperation(ticket_management_reports, {
            input: {
              organization_id: data.organization.organization_id,
              user_email_id: this.userselect.user_id,
              user_name: this.userselect.full_user_name,

              genrated_by_email: data.user.user_email_id,
            },
          })
        );
        this.buttonload = false;

        var response = JSON.parse(result.data.ticket_management_reports);

        if (response.Status == "SUCCESS") {
          this.buttonload = false;
          this.ticketRecords = [];
          this.get_report();
          this.SnackBarComponent = {
            SnackbarVmodel: true,
            SnackbarColor: "green",
            SnackbarText: response.Message,
            timeout: 5000,
            Top: true,
          };
        } else {
          this.buttonload = false;
          this.SnackBarComponent = {
            SnackbarVmodel: true,
            SnackbarColor: "red",
            SnackbarText: response.Message,
            timeout: 5000,
            Top: true,
          };
        }
      } catch (error) {
        this.tableLoading = false;
        this.buttonload = false;
        this.SnackBarComponent = {
          SnackbarVmodel: true,
          SnackbarColor: "red",
          SnackbarText: error.errors[0].message,
          timeout: 5000,
          Top: true,
        };
      }
    },

    async download_invoice(url) {
      let firstName = this.$store.getters.GetUserObj?.organization?.organization_team_id;
      let fileName = firstName ? firstName + "_" + url.report_type_name + ".xlsx" : "_" + url.report_type_name + ".xlsx";
      // var fileName = url.report_type_name + ".xlsx";
      axios({
        url: url.generationreport_url,
        method: "GET",
        responseType: "blob", // Set the response type to blob
      })
        .then((response) => {
          const blob = new Blob([response.data], {
            type: response.headers["content-type"],
          });

          // Use the FileSaver library to save the file
          FileSaver.saveAs(blob, fileName);
        })
        .catch((error) => {
          console.error("Error downloading the file:", error);
        });
    },
    fetch_user_data() {
      this.userArray = [];
      this.orgUsers.forEach((element) => {
        if (
          element.user_status == "ACTIVE" &&
          element.user_type != "CHATBOT" &&
          element.user_type != "MEMBER"
        ) {
          this.userArray.push({
            full_user_name: element.full_user_name,
            user_id: element.user_email_id,
          });
        }
      });
      this.userArray.unshift({
        full_user_name: "All",
        user_id: "ALL",
      });
      this.userselect = this.userArray[0];
    },
    get_dateformate(val) {
      return formatedatetime(val);
    },
  },
};
</script>

<style>
</style>