<template>
  <div>
    <v-card flat>
  
      <!-- Data Table -->
      <v-card-text class="pa-4">
        <v-data-table
          :height="height"
          :fixed-header="true"
          :search="globalSearch"
          :headers="headers"
          :items="filteredItems"
          :items-per-page="itemsPerPage"
          :page="currentPage"
          :server-items-length="totalCount"
          :loading="tableLoading"
          class="modern-data-table"
          density="comfortable"
          hover
          multi-sort
          hide-default-footer
          @update:sort-by="handleSortChange"
        >
          <template v-slot:no-data>
            <div class="text-center py-8">
              <!-- <v-icon size="64" color="grey lighten-1" class="mb-4"
                >mdi-file-document-outline</v-icon
              > -->
              <div class="text-h6 grey--text mb-2">No Reports Found</div>
              <div class="text-body-2 grey--text">
                Try adjusting your search criteria.
              </div>
            </div>
          </template>

          <template v-slot:loading>
            <div class="text-center py-8">
              <v-progress-circular
                indeterminate
                color="primary"
                size="32"
                class="mb-4"
              ></v-progress-circular>
              <div class="text-body-2 grey--text">Loading reports...</div>
            </div>
          </template>

          <!-- Workflow Name -->
          <template v-slot:[`item.report_name`]="{ item }">
            <div class="d-flex align-center">
              <!-- <v-icon size="20" color="primary" class="mr-3"
                >mdi-file-document</v-icon
              > -->
              <div>
                <div class="font-weight-medium text-body-2">
                  {{ item.report_name }}
                </div>
              </div>
            </div>
          </template>

          <!-- From Date -->
          <template v-slot:[`item.report_from_date`]="{ item }">
            <div class="d-flex align-center">
              <!-- <v-icon size="16" color="grey" class="mr-2"
                >mdi-calendar-start</v-icon
              > -->
              <span class="caption">{{
                fetch_value(item.report_from_date)
              }}</span>
            </div>
          </template>

          <!-- To Date -->
          <template v-slot:[`item.report_to_date`]="{ item }">
            <div class="d-flex align-center">
              <!-- <v-icon size="16" color="grey" class="mr-2"
                >mdi-calendar-end</v-icon
              > -->
              <span class="caption">{{
                fetch_value(item.report_to_date)
              }}</span>
            </div>
          </template>

          <!-- Generated On -->
          <template v-slot:[`item.report_created_on`]="{ item }">
            <div class="d-flex align-center">
              <!-- <v-icon size="16" color="grey" class="mr-2"
                >mdi-calendar-clock</v-icon
              > -->
              <span class="caption">{{
                fetch_value(item.report_created_on)
              }}</span>
            </div>
          </template>

          <!-- Generated By -->
          <template v-slot:[`item.report_created_by`]="{ item }">
            <div class="d-flex align-center">
              <!-- <v-icon size="16" color="primary" class="mr-2"
                >mdi-account</v-icon
              > -->
              <span class="caption">{{ item.report_created_by }}</span>
            </div>
          </template>

          <!-- Status -->
          <template v-slot:[`item.report_generation_status`]="{ item }">
            <div class="d-flex align-center">
              <v-icon
                size="16"
                class="mr-2"
                :color="
                  item.report_generation_status === 'COMPLETED'
                    ? 'green'
                    : item.report_generation_status === 'IN PROGRESS'
                    ? 'orange'
                    : 'red'
                "
              >
                {{
                  item.report_generation_status === "COMPLETED"
                    ? "mdi-check-circle"
                    : item.report_generation_status === "IN PROGRESS"
                    ? "mdi-clock"
                    : "mdi-close-circle"
                }}
              </v-icon>
              <span
                :class="
                  item.report_generation_status === 'COMPLETED'
                    ? 'green--text'
                    : item.report_generation_status === 'IN PROGRESS'
                    ? 'orange--text'
                    : 'red--text'
                "
                class="caption"
              >
                {{
                  item.report_generation_status === "COMPLETED"
                    ? "COMPLETED"
                    : item.report_generation_status === "IN PROGRESS"
                    ? "IN PROGRESS"
                    : "NO RECORDS"
                }}
              </span>
            </div>
          </template>

          <!-- Actions -->
          <template v-slot:[`item.actions`]="{ item }">
            <div class="d-flex align-center justify-center">
              <v-icon
                v-if="item.report_generation_status === 'COMPLETED'"
                @click="download_item(item)"
                color="primary"
                class="cursor-pointer"
                size="20"
              >
                mdi-download
              </v-icon>
              <div v-else class="d-flex align-center">
                <v-icon size="16" color="grey" class="mr-2">mdi-minus</v-icon>
                <span class="caption">-</span>
              </div>
            </div>
          </template>
        </v-data-table>

        <!-- Modern Table Footer -->
        <div class="table-footer">
          <div class="footer-info">
            {{  
              totalCount === 0
                ? "No Results"
                : `Showing ${filteredItems.length} of ${totalCount} reports`
            }}
          </div>
          <div class="pagination-controls">
            <v-btn
              :disabled="currentPage === 1"
              variant="text"
              size="small"
              class="pagination-btn"
              @click="currentPage = currentPage - 1"
              style="color: #666 !important;"
            >
              Previous
            </v-btn>
            <div class="page-numbers">
              <v-btn
                v-for="page in visiblePages"
                :key="page"
                :variant="page === currentPage ? 'elevated' : 'text'"
                size="small"
                :class="page === currentPage ? 'active-page' : 'inactive-page'"
                @click="currentPage = page"
                :style="page === currentPage ? 'background: #DB4C77 !important; color: white !important;' : 'color: #666 !important;'"
              >
                {{ page }}
              </v-btn>
            </div>
            <v-btn
              :disabled="currentPage === pageCount"
              variant="text"
              size="small"
              class="pagination-btn"
              @click="currentPage = currentPage + 1"
              style="color: #666 !important;"
            >
              Next
            </v-btn>
          </div>
        </div>
      </v-card-text>
    </v-card>
  </div>
</template>

<script>
import { format_Date } from "@/JsonFiles/DateFormate.js";
import { list_all_reports } from "@/graphql/queries.js";
import { API, graphqlOperation } from "aws-amplify";
import axios from "axios";
const FileSaver = require("file-saver");

export default {
  props:{
      globalSearch:{
        type:String,
        default :"ALL"
      }
  },
  data() {
    return {
      search: "",
      currentPage: 1,
      itemsPerPage: 20,
      tableLoading: false,
      height: 0,
      tableData: [],
      headers: [
        { title: "Workflow Name", key: "report_name", sortable: false },
        { title: "Form Date", key: "report_from_date", sortable: false },
        { title: "To Date", key: "report_to_date", sortable: false },
        { title: "Generated On", key: "report_created_on", sortable: false },
        { title: "Generated By", key: "report_created_by", sortable: false },
        { title: "Status", key: "report_generation_status", sortable: false },
        { title: "Actions", key: "actions", sortable: false },
      ],
    };
  },

  computed: {
     globalSearch(){
      this.currentPage = 1
    },
filteredItems() {
  if (!this.globalSearch || this.globalSearch.trim() === "") {
    return this.tableData;
  }

  const search = this.globalSearch.toLowerCase();

  return this.tableData.filter(row =>
    Object.values(row).some(val =>
      val &&
      String(val).toLowerCase().includes(search)
    )
  );
}
,
    paginatedItems() {
      const start = (this.currentPage - 1) * this.itemsPerPage;
      return this.filteredItems.slice(start, start + this.itemsPerPage);
    },
    pageCount() {
      return Math.ceil(this.filteredItems.length / this.itemsPerPage);
    },
    startItem() {
      return this.filteredItems.length === 0
        ? 0
        : (this.currentPage - 1) * this.itemsPerPage + 1;
    },
    endItem() {
      return Math.min(
        this.currentPage * this.itemsPerPage,
        this.filteredItems.length
      );
    },
    totalCount() {
      return this.filteredItems.length;
    },
    visiblePages() {
      const pages = [];
      const start = Math.max(1, this.currentPage - 2);
      const end = Math.min(this.pageCount, this.currentPage + 2);
      for (let i = start; i <= end; i++) {
        pages.push(i);
      }
      return pages;
    },
  },

  watch: {
  
    currentPage(newVal) {
      // When the page changes, scroll to top of table (optional)
      const table = document.querySelector(".modern-data-table");
      if (table) table.scrollIntoView({ behavior: "smooth", block: "start" });
    },
  },

  created() {
    this.height = window.innerHeight - 250;
    this.fetch_records();
  },

  methods: {
    fetch_value(val) {
      return format_Date(val);
    },

    async fetch_records() {
      this.tableLoading = true;
      const user = this.$store.getters.GetUserObj;

      try {
        const result = await API.graphql(
          graphqlOperation(list_all_reports, {
            input: {
              organization_id: user.organization.organization_id,
              report_type: "WORKFLOW",
            },
          })
        );

        const response = JSON.parse(result.data.list_all_reports);
        if (response.Status === "SUCCESS") {
          this.tableData = response.data || [];
        }
      } catch (error) {
        this.$store.commit("SetSnackbar", {
          SnackbarVmodel: true,
          SnackbarColor: "red",
          SnackbarText: error.errors?.[0]?.message || "Error fetching records",
          timeout: 5000,
          Top: true,
        });
      } finally {
        this.tableLoading = false;
      }
    },

    async download_item(item) {
      const fileName = `${item.report_name}.xlsx`;

      try {
        const response = await axios({
          url: item.report_url,
          method: "GET",
          responseType: "blob",
        });

        const blob = new Blob([response.data], {
          type: response.headers["content-type"],
        });

        FileSaver.saveAs(blob, fileName);
      } catch (err) {
        this.$store.commit("SetSnackbar", {
          SnackbarVmodel: true,
          SnackbarColor: "red",
          SnackbarText: "Download failed.",
          timeout: 4000,
          Top: true,
        });
      }
    },

    handleSortChange(value) {
      // Implement the logic to handle sort change
    },

    updatePageItems(value) {
      // Implement the logic to update page items
    },
  },
};
</script>

<style scoped>
.font-weight-medium {
  font-weight: 500;
}

/* Modern Data Table */
.modern-data-table {
  background: white;
  border-radius: 12px;
  overflow: hidden;
  box-shadow: 0 2px 8px rgba(0, 0, 0, 0.1);
}

/* Table Footer */
.table-footer {
  display: flex;
  justify-content: space-between;
  align-items: center;
  padding: 16px 24px;
  background: white;
  border-top: 1px solid #e0e0e0;
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
}

.footer-info {
  font-size: 14px;
  color: #666;
  font-weight: 400;
}

.pagination-controls {
  display: flex;
  align-items: center;
  gap: 8px;
}

.pagination-btn {
  font-size: 14px !important;
  font-weight: 500 !important;
  text-transform: none !important;
  min-width: 80px !important;
}

.page-numbers {
  display: flex;
  gap: 4px;
}

.active-page {
  background: #DB4C77 !important;
  color: white !important;
  font-weight: 500 !important;
  min-width: 36px !important;
  height: 36px !important;
}

.inactive-page {
  color: #666 !important;
  font-weight: 400 !important;
  min-width: 36px !important;
  height: 36px !important;
}

.cursor-pointer {
  cursor: pointer;
  transition: all 0.2s ease;
}

.cursor-pointer:hover {
  transform: scale(1.05);
}

.search-pill :deep(.v-field__input) {
  padding-top: 0;
  padding-bottom: 0;
  min-height: 32px;
}

.search-pill :deep(.v-field__prepend-inner) {
  padding-inline-start: 12px;
}

.modern-data-table :deep(.v-data-table__wrapper) {
  border-radius: 12px;
}

.modern-data-table :deep(.v-data-table__tbody tr:hover) {
  background-color: rgba(var(--v-theme-primary), 0.04) !important;
}

.modern-data-table :deep(.v-data-table__tbody tr) {
  transition: background-color 0.2s ease;
}
</style>
