projects:
  stichh_portal:
    schemaPath: src/graphql/schema.json
    includes:
      - src/graphql/**/*.js
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: javascript
        generatedFileName: ''
        docsFilePath: src/graphql
        region: us-east-1
        apiId: 2kcyn2aqc5dxnjbsaostuhxewu
        maxDepth: 7
extensions:
  amplify:
    version: 3
