<template>
    <div>
        <v-card>
            
            <v-data-table 
            :headers="headers"
            :loading="loading"
            :items="Reportitems"
            >
             <template #item.Report = {item}>
                <v-icon color="primary">mdi-download</v-icon>

             </template>
            </v-data-table>
        </v-card>
    </div>
</template>
<script>


export default{
    data(){
        return{
            loading: false, 
            headers : [
                {title: "Report Type" , value:"report_type"},
                {title:"User Type" , value: "user_type"},
                                {title:"Generated For" , value: "Generated_for"},
                {title:" Generated On" , value: "Generated_on"},
                {title:"Generated By", value:"Generted_by"},
                {title:"Status", value:"Status"},
                {title:"Report",value:"Report"}

            ],
            Reportitems:[
                {report_type :"Daily Proof of Work", user_type:"Vk",
                    Generated_for :"2025-06" , Generated_on:"11/11/11",Generted_by :"Vishank",
                     Status :"ACTIVE"

                }
            ]
        }
    }
}
</script>